spring:
  application:
    name: turbine-server
turbine:
  instanceUrlSuffix: :8080/hystrix.stream
  aggregator:
        clusterConfig: default
InstanceDiscovery:
  impl: io.fabric8.kubeflix.turbine.TurbineDiscovery