---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    hystrix.enabled: "true"
    project: "${project.artifactId}"
    provider: "fabric8"
    version: "${project.version}"
    group: "io.fabric8.kubeflix.examples"
  name: "hello-hystrix"
spec:
  ports:
  - port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    hystrix.enabled: "true"
    project: "hello-hystrix"
    provider: "fabric8"
    group: "io.fabric8.kubeflix.examples"
  type: "LoadBalancer"
